apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-nodejs-app
  labels:
    app: welcome-nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: welcome-nodejs-app
  template:
    metadata:
      labels:
        app: welcome-nodejs-app
    spec:
      containers:
      - name: welcome-nodejs-app
        image: anitajinu/welcome-nodejs-app-devops:v1-release
        ports:
        - containerPort: 8765
